kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: plone-k8s
  labels:
    app: plone-k8s
spec:
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "700m"
      memory: "768Mi"
  output:
    to:
      kind: ImageStreamTag
      name: 'plone-k8s:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: https://github.com/pflaeging/plone-delpoy-k8s.git
      ref: main
    contextDir: /plone-k8s
  triggers:
    - type: ConfigChange
  runPolicy: Serial
