apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- buildconfig.yaml
- imagestream.yaml

secretGenerator:
  - name: read-repo
    files:
    - .gitconfig=dot-gitconfig.ini

generatorOptions:
  disableNameSuffixHash: true
