apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - persistentvolumeclaim.yaml

secretGenerator:
  - name: database
    envs:
    - database.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true