apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- Deployment-nginx.yaml
- Deployment-plone.yaml
- Deployment-zeo.yaml
- PersistentVolumeClaim-data.yaml
- Route.yaml
- Route-master.yaml
- Service-nginx.yaml
- Service-plone.yaml
- Service-zeo.yaml

configMapGenerator:
  - name: nginx
    files:
      - nginx-revproxy.conf

generatorOptions:
  disableNameSuffixHash: true

images:
- name: plone:latest
  newName: default-route-openshift-image-registry.apps.mirkwood.pfpk.pro/develop/plone-k8s
  newTag: latest